### ISSUE TITLE
Unable to retrieve Tab info for YouTube Speed Memory

### ISSUE THREAD

**Issue by nikolayhg** [andrewbrey/youtube-speed-memory#3]
When I open a YouTube video, I get the console errors: `Unable to retrieve Tab info for YouTube Speed Memory` and `Unable to retrieve Tab info for YouTube Speed Memory`.

Test environment: Chrome 69.0.3497.81 (Official Build) (64-bit)

**Comment by andrewbrey** [comment]
@nikolayhg When you refresh the YouTube page, does this behavior persist? This is something that can occur in cases where YT did not load quickly enough and the extension stops trying to register itself with the page. In this situation, reloading YT should solve the issue.

This issue will be something included in the large scale refactor of the whole extension, so keep an eye on the project and issue status updates that will be coming soon.

**Comment by nikolayhg** [comment]
yes. I tried refreshing, same error.

**Comment by andrewbrey** [comment]
Hm, I'm not sure what is going on here, I've never experienced this symptom across refreshes. You could try reinstalling the extension, but barring that I don't have a lot of intuition about what's going on at this moment. Improving the predictability of the extension will be a top priority during the rewrite, so for the time being, if reinstalling doesn't work, you'll just have to sit tight while I work on the rewrite :)

**Comment by nikolayhg** [comment]
reinstalled it and deactivated potential collision extension, but get same error.

**Comment by andrewbrey** [comment]
Ok shoot - the only thing that comes to mind is that your youtube page is not loading fast enough (from YouTube Speed Memory's perspective) or that you have an adblocker (or something) that is blocking the specific elements the extension expects. All it waits to load are the channel name, the video id, and the channel artwork, so I'm not sure what could be blocked by an adblocker, i.e. that seems unlikely to be the culprit. For now you may just need to sit tight while I find the time to get to the updates (or feel free to make a pull request to do them yourself if you are able 😄). I'll update this issue when I've made the updates for you to test.

**Comment by nikolayhg** [comment]
Thanks! I can wait. FYI: I deactivated all blocking extensions for the test. The video starts in less than 2 secs.

**Comment by andrewbrey** [comment]
@nikolayhg I finally found out what's happening with this bug. The version of YouTube that you were being served was different than what I was being served (Google does market-subset testing with UI changes). This is why my extension was working fine and yours was not. Today, I started receiving the "new" YouTube that you had been getting and my extension stopped working too. I've made updates that will ensure that both of these versions of the site will work with the extension. I'll be pushing it to the store in the next few minutes, so you should be able to update your extension within the hour and have it start working again.

I'm going to close this issue, but if your issue persists, I can reopen it.

Cheers!

**Comment by nikolayhg** [comment]
awesome, thank you!
